### ISSUE TITLE
Proguard Issue

### ISSUE THREAD

**Issue by munnadroid** [nkzawa/socket.io-android-chat#107]
I am getting below response when proguard is turned off.

`[{
	"nameValuePairs": {
		"message": "Hello I am message"
	}
}]`

But when I enable proguard, received below message:
`[{
	"a": {
		"message": "Hello I am Message"
	}
}]`

I have added proguard rules for gson and my model package. The only **nameValuePairs** key is replaced by **a**, other keys are fine as it should be.
Has anyone faced the same issue with proguard?

**Comment by tmjvonboss** [comment]
What proguard options are you using that affect gson? Just curious, I never use gson to begin with honestly

(pretty sure this is an issue you wanna post on a gson repository, of there is one)

why using proguard and not r8?

**Comment by munnadroid** [comment]
Below is the proguard rules I used for gson:

> -keepattributes Signature
> 
> -keepattributes *Annotation*
> 
> -dontwarn sun.misc.**
> 
> -keep class com.google.gson.examples.android.model.** { <fields>; }
> 
> -keep class * implements com.google.gson.TypeAdapterFactory
> -keep class * implements com.google.gson.JsonSerializer
> -keep class * implements com.google.gson.JsonDeserializer
> 
> -keepclassmembers,allowobfuscation class * {
>   @com.google.gson.annotations.SerializedName <fields>;
> }

I think it has nothing to do with gson. 
After getting this response `[{ "nameValuePairs": { "message": "Hello I am a message" } }]`, then only I am converting this string to data class using gson. The problem is I am getting this `[{ "a": { "message": "Hello I am Message" } }]` string when I enable proguard and I am only using gson after getting above string response.

**Comment by tmjvonboss** [comment]
Okay so let me know if I get this correctly

without proguard/r8:

1. you connect to server
2. you receive message
3. you log the message
4. the message is:
`[{ "nameValuePairs": { "message": "Hello I am a message" } }]`

With proguard/r8:
1. you connect to server
2. you receive message
3. you log the message
4. the message is:
`[{ "a": { "message": "Hello I am a message" } }]`

So where are you logging the message/response, and when are you logging the response?
I would assume in the app (where) and after deserialization (after gson, when)
If I misunderstood, then please provide code example


Regardless, can you confirm from the server side what response is being sent? That's what I would do, because if the server sends the same message twice then I'm inclined to say this is a gson issue rsther than a socket.io issue.

Maybe try an implementation in regular org.json to see if that gives same result

Is this issue breaking the app or is it changing the key value but it runs fine even though it changed the key value?

**Comment by munnadroid** [comment]
Here is the code snippet:
```
mSocket?.on("message", Emitter.Listener {

            Log.v(TAG,"Received message: ${Gson().toJson(it)}") //This is where I got those response

            val messages: List<Message?>? =
                Gson().fromJson(Gson().toJson(it), object : TypeToken<ArrayList<Message?>?>() {}.type)
        })
```

Above response is from this line, `Log.v(TAG,"Received message: ${Gson().toJson(it)}")`. You can see those messages are before using gson.

**Comment by tmjvonboss** [comment]
That is not before using gson, you clearly instantiate Gson there on the same line
`Gson()`
That is using gson
To further compound on that
`toJson` is a method inside the gson library, can't call it without using gson

Try logging `it` before using gson
Not sure what the data type of `it` is but `Log.v(TAG,"Received message: ${it}")` would be without gson

**Comment by munnadroid** [comment]
Yes, you are correct, I didn't notice that. Google gson is the problem here. Thank you for helping me out.
