### ISSUE TITLE
Receiving Arrays from server

### ISSUE THREAD

**Issue by shubhendumadhukar** [nkzawa/socket.io-android-chat#96]
One of my custom events "updateUserList" returns a array of users currently active in the application. Is there a way I can get that array on the client side?

My server is sending data as
`socket.emit('updateUserList', activeUsersArray);`

However, the sample code demonstrates that the data has to be (I could be wrong) a JSONObject.
`JSONObject data = (JSONObject) args[0];`

**Comment by tmjvonboss** [comment]
You could attempt two ways to fix that


1. Instead of casting your object to a JSONObject, just try casting it to a JSONArray directly
`JSONArray data = (JSONArray) args[0];`

2. avoid the problem all together by making the server return a json object containing the list within

something like this:

{"userList":["user1", "user2"]}

This is a JSONObject and the key "userList" contains the list of users

**Comment by shubhendumadhukar** [comment]
Thanks a lot. The first way works for me.
`JSONArray data = (JSONArray) args[0];`

I already have a web application running and I didn't foresee the android client, and now I don't want to change any bit of server side code unless absolutely necessary.
Anyway, thanks!
